### ISSUE TITLE
Server is pinging excessively

### ISSUE THREAD

**Issue by RealRONiN** [mc-protection/known-bugs#4] opened 2022-01-20 07:04 UTC
### Description

https://discord.com/channels/665338724703273000/933391331210956842/933391430934745158

### Stackrace print/logs link

https://cdn.discordapp.com/attachments/933391331210956842/933391430330753084/unknown.png

### Expected behavior

-

### Actual behavior

-

### Steps to reproduce this bug/error.

-

### Product version

Unspecified.

### Agreement

- [X] I am running the latest version of respective MCP product I'm having issues with, from https://mc-protection.eu/products.
- [X] I have checked for and confirmed there isn't already a similar issue opened.
- [X] My version of Spigot/Paper/fork is supported by respective MCP product, this does not apply to Atomspigot, so just check this box in that case.

**Comment by NoJokeFNA** [comment] 2022-01-20 07:40
Duplicate of #2

**Closed as completed by NoJokeFNA** 2022-01-20 07:40 UTC
Labels: bug, duplicate
